### ISSUE TITLE
Milestone Goal: Login

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#42]
**User Story:**
As a Prevention Point employee, I need a central web app where I can login, so that I can access the system from any location

**Acceptance Criteria:**
- [x] User needs to be able to sign in with a user name and password
- [x] User needs to define what location they are logging in for
- [x] User needs to be able to create a new account
- [x] User needs to be able to reset their password

RELATED ISSUES:
#3

**Comment by grahamalama** [comment]
Started in https://github.com/CodeForPhilly/prevention-point/pull/19

**Comment by kyle-hauber** [comment]
@mariekers - Does a user need to be able to reset their password or something a Prevention Point admin will handle? Do they have a preference?
