### ISSUE TITLE
Overall Milestone - User Story for Front Desk Check-in

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#67]
**User Story**
As a front desk employee, I need to be able to input a participant's information into the system, so that I can check them in and manage the queue

**Acceptance Criteria:**
Should results in a clickable prototype that enables the following:
- [x] Upon logging in, front desk employees should land on a page that give them the option to search for a participant or view the current wait list
- [x] FDE should be able to check-in a participant and add them to the waitlist. This can be done by:
    - [x] searching for an existing participant and adding them
    - [x] adding a new participant to the system
- [x] Adding a new participant should load a registration form. Registration form should include the following information
    - [x] First Name
    - [x] Last Name
    - [x] Date of Birth
    - [x] User ID
    - [x] Race
    - [x] Gender
    - [x] Insurance Status
    - [x] Insurance Provider
    - [x] Program
    - [x] Service
- [x] FDE should be able to use the waitlist to manage participants' appointments (purposely leaving this open ended - could be simple time stamps that they manage, could be a drag and drop system, could be something else.  Let's figure out what works best!)

**Comment by kyle-hauber** [comment]
cleaning up old issues:  confirming that we reviewed this together and a clickable prototype was shared with Prevention Point which yielded feedback that informed revisions

**Comment by kyle-hauber** [comment]
all mocks can be found in the Prevention Point Figma project:  https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=59%3A15
